### ISSUE TITLE
Question regarding Cluster Distribution

### ISSUE THREAD

**Issue by ch-ho00** [jsvir/idc#1]
Hi. Thank you for open sourcing this great work. I am currently making use of my own tabular data to perform unsupervised clustering using your code. 

My dataset size is 564907 and currently my cluster distribution looks like below 

```
{0: 8759, 1: 545795, 2: 4261, 3: 2283, 4:3809}

```

Ideally I want the distribution to be a more dispersed than it is now. Do you have any suggestions on what parameters or modification in the model level I might want to look into? 
Thanks in advance!

**Comment by jsvir** [comment]
Hi, 
What are the values of your features? Do you apply any special preprocessing? Is it categorial or numeric? 

Without knowing anything about your data we would suggest to try to increase the number of clusters and then merge them by some heuristic.

**Comment by ch-ho00** [comment]
Yes increasing cluster number sounds like a good idea. Thank you for the advice!
And to be more detailed about my dataset I have less than 100 features on a tabular data without annotation. 
So I have been trying to unsupervised cluster and through a lower capacity model.
