### ISSUE TITLE
PBMC-dataset

### ISSUE THREAD

**Issue by zz978233034** [jsvir/idc#2]
Thank you for your excellent work! I didn't find the dataset pbmc_y.npz when I tried to reproduce the paper results.Could you please provide me with the corresponding labeled data set? Thank you very much

**Comment by Felipe-Rafael-Rosa** [comment]
I think this will help you.
https://bit.ly/4evXrQ6
I put the necessary dlls in the archive

**Comment by jsvir** [comment]
Sure. Added in the data directory

**Comment by zz978233034** [comment]
Could you please provide the configuration file by the way?  Thank you very much!

**Comment by jsvir** [comment]
I think the example we have in the repo has the required parameters for PBMC [here](https://github.com/jsvir/idc/blob/main/cfg/cfg_run.yaml).
